module.exports = {
    multiply: require("./lib/multiply"),
    lighten: require("./lib/lighten"),
    darken: require("./lib/darken"),
    darkercolor: require("./lib/darkercolor"),
    lightercolor: require("./lib/lightercolor"),
    lineardodge: require("./lib/lineardodge"),
    linearburn: require("./lib/linearburn"),
    difference: require("./lib/difference"),
    screen: require("./lib/screen"),
    exclusion: require("./lib/exclusion"),
    overlay: require("./lib/overlay"),
    softlight: require("./lib/softlight"),
    hardlight: require("./lib/hardlight"),
    colordodge: require("./lib/colordodge"),
    colorburn: require("./lib/colorburn"),
    linearlight: require("./lib/linearlight"),
    vividlight: require("./lib/vividlight"),
    pinlight: require("./lib/pinlight"),
    hardmix: require("./lib/hardmix"),
    subtract: require("./lib/subtract"),
    divide: require("./lib/divide")
};
